# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/mediatek/ims/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

# Включает все Android.mk во всех подпапках
include $(call all-makefiles-under,$(LOCAL_PATH))

# Сообщает системе Soong (которая обрабатывает .bp), что нужно искать модули здесь
#$(call find-copy-subdir-files,*,$(LOCAL_PATH),$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay)
