# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/mediatek/ims/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/mediatek/ims

PRODUCT_COPY_FILES += \
    vendor/mediatek/ims/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc

PRODUCT_PACKAGES += \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libsignal \
    libsink-mtk \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.videotelephony@1.0 \
    ImsService \
    MtkGbaService \
    MtkTelephonyAssist \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-legacy \
    mediatek-wfo-legacy \
    vtservice
